package com.og.CouponSystemJB.rest;

/*----------------- IMPORTS -----------------------------------------------------------------------------------------*/

/*-------------------- java --------------------*/

/*---------- util ----------*/

import java.util.HashMap;
import java.util.Map;

/*-------------------- springframework --------------------*/

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * This configuration class holds the HashMap of tokens. The tokensMap collection maps a random String generated by
 * the LoginController class (the token) to a ClientSession. Each ClientSession is mapped to a unique and random token
 * which will be sent to the User via a cookie. When the User sends an HTTP request his cookie will be checked for
 * the token and it will be matched with the correct ClientSession representing that User.
 */
@Configuration
public class RestConfiguration {

    /**
     * The collection (HashMap) that maps the random String tokens to their respective ClientSession. Each User who
     * logged in will hold inside its cookie the token that maps to the respective ClientSession.
     *
     * @return HashMap of tokens to the ClientSessions.
     */
    @Bean(name = "tokens")
    public Map<String, ClientSession> tokensMap() {
        return new HashMap<>();
    }

}